// <auto-generated />
using System;
using Employeeskillmanagment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employeeskillmanagment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240105072457_MigrationsForEmployeeFieldAdded")]
    partial class MigrationsForEmployeeFieldAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Employeeskillmanagment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DOJ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOJ = new DateOnly(2022, 11, 3),
                            Designation = "Developer",
                            Email = "sonalipandagre2@gmail.com",
                            FirstName = "Sonali",
                            LastName = "Pandagre"
                        },
                        new
                        {
                            Id = 2,
                            DOJ = new DateOnly(2022, 11, 3),
                            Designation = "Tester",
                            Email = "rashmi@gmail.com",
                            FirstName = "Rashmi",
                            LastName = "Bansal"
                        },
                        new
                        {
                            Id = 3,
                            DOJ = new DateOnly(2022, 10, 3),
                            Designation = "Designer",
                            Email = "aditya@gmail.com",
                            FirstName = "Mayuri",
                            LastName = "Shirbhate"
                        },
                        new
                        {
                            Id = 4,
                            DOJ = new DateOnly(2021, 10, 3),
                            Designation = "Architecture",
                            Email = "animasahu10@gmail.com",
                            FirstName = "Anima",
                            LastName = "Sahu"
                        },
                        new
                        {
                            Id = 5,
                            DOJ = new DateOnly(2020, 10, 4),
                            Designation = "Sr. Developer",
                            Email = "divydas20@gmail.com",
                            FirstName = "Divya",
                            LastName = "das"
                        },
                        new
                        {
                            Id = 6,
                            DOJ = new DateOnly(2021, 12, 4),
                            Designation = "Frotend Developer",
                            Email = "ankushpandagre100@gmail.com",
                            FirstName = "Ankush",
                            LastName = "Pandagre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
